### ISSUE TITLE
Entity Type-Detector "Duplicates found for xxx"

### ISSUE THREAD

**Issue by JoachimEngelmann** [ioBroker/ioBroker.lovelace#153]
Hi,

i have two Aqara Temperature Sensors connected via Zigbee Adapter and set them to the correct room (e.g. bedroom, living room), function (sensor) and a value-role in the object tree (see atattched screenshot). The auto type detetction for entities works for the first device, while during the detection of the second device the log says "Duplicates found for sensor.temperature" (see atattched screenshot).

Is this a fault in my setup? Expected behaviour would be that each sensor.Temperature gets an unique value for auto type detection. Maybe a comibnation with room, function and value name.

Screenshots
Log output:
<img src="https://user-images.githubusercontent.com/32760573/105575840-dff39380-5d6e-11eb-9a3f-ac5106d87e81.PNG" data-canonical-src="https://user-images.githubusercontent.com/32760573/105575840-dff39380-5d6e-11eb-9a3f-ac5106d87e81.PNG" width="600"/>

Object tree:
<img src="https://user-images.githubusercontent.com/32760573/105575845-e71aa180-5d6e-11eb-9ecb-d23f1ed0e47f.PNG" data-canonical-src="https://user-images.githubusercontent.com/32760573/105575845-e71aa180-5d6e-11eb-9ecb-d23f1ed0e47f.PNG" width="600"/>

Versions:
 - Adapter version: 1.4.2
 - JS-Controller version: 3.2.8
 - Node version: 14.15.4
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by Garfonso** [comment]
It is not technically an issue in your setup... hm.. It seems more like a bad conicidence of multiple circumstances.

Usually the entity id is derived from the device name, i.e. `Wohnzimmer\Schlafzimmer Aqara Temp` in your case, which would be unique and most often is. But in the case of temperature, for some reason I have to check, it is derived from the state which in your case yields just `temperature`. (Humidity is the same issue and maybe that is the culprit here, both are in the domain `sensor` in lovelace, so there need to be two unique entity ids for the device, here)

I checked with my zigbee setup and my aquara sensor and there I see something else that is different: On my zigbee device all states inherit the name of the device, i.e. on my system the name of the temperature state is `Schlafzimmer Aquara Temp Temperature`, which is again unique. My device setup is a bit older, though. Maybe they did change that? 

So changing the name of the temperature (and if you care for them the humidity) states would be a work around for the Problem in 1.4.2.

I do not really like the `duplica found` thing. But in many cases it seems necessary, because devices seem to be detected multiple times a lot (not 100% sure here... hm). One way to change it would be to still use the device name for temperature sensors but add `temperature` as postfix manually. Will think about that a bit.

**Comment by mskyda** [comment]
Hi @Garfonso and @JoachimEngelmann I have the same issue with two Aqara Sensors. Here's my setup:

![image](https://user-images.githubusercontent.com/13311882/107741408-61ef3080-6d0d-11eb-976f-372081361756.png)

And Lovelace panel shows only the last added sensor (`Badezimmer` in my case):

![image](https://user-images.githubusercontent.com/13311882/107741523-a2e74500-6d0d-11eb-9e01-38aee8726aae.png)

When I remove `Room` and `Function` from `Badezimmer` object, then `Balkon` becomes visible instead:

![image](https://user-images.githubusercontent.com/13311882/107741648-dd50e200-6d0d-11eb-881d-b8a79f818f45.png)

Would appreciate any help.

**Comment by Garfonso** [comment]
Workaround currently is: Rename the .temperature and .humidity States (i.e. the name in the second column).

I will try to fix this issue in one of the next versions.

**Comment by Garfonso** [comment]
still investigating.

**Comment by Garfonso** [comment]
should be fixed in latest. Please tests with 2.0.0
