### ISSUE TITLE
"Run as" broken + "Could not find default user admin" is logged

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.lovelace#532]
**Describe the bug**  

I have a very strange situation with one of my Lovelace instances. The instance in question is "Run as" the Guest user since it is used by guests. They should not be able to control every entity. The setup has been working with 3.x before.

<img width="411" alt="2024-05-16_18-29-52" src="https://github.com/ioBroker/ioBroker.lovelace/assets/16245/96464e0c-1a6e-4693-8c92-57911c73fc9f">

First off, when the adapter starts it logs 

```
Could not find default user Administrator - Using admin - Please update your configuration.
```

How should I update my configuration? It also seems like "admin" exists:

<img width="588" alt="2024-05-16_18-28-57" src="https://github.com/ioBroker/ioBroker.lovelace/assets/16245/085ede52-a4bd-4c86-8ae2-2ed0e380a238">

Despite the instance is running as the "Guest" user users can control entities they should not be able to control.

E.g. the entity in question is owned by me and the Administrators group and "others" cannot write the state:

<img width="680" alt="2024-05-16_18-31-40" src="https://github.com/ioBroker/ioBroker.lovelace/assets/16245/c9b18f6d-d48c-4c47-91d7-04a902a4d2ea">

Yet when I switch the toggle associated with the entity, the state changes.

**Comment by agross** [comment]
It's probably a good idea to

1. Let the admin select the "Run as" user by name
2. ...but write the user ID to the adapter config
3. ...and later check `defaultUserObject` based on the ID instead of the name

The issue in my case is that the `guest` user ID has the `Guest` user name. When selecting `Guest` on the UI, `defaultUser: 'guest'` is written to the adapter config but later when checking for the `defaultUserObject` [the user **name** `Guest` is compared to the saved user **ID** `guest`](https://github.com/ioBroker/ioBroker.lovelace/blob/e0f9ac6d2e4a5f3d8e902d38439ea126456c3502/lib/modules/person.js#L79).

**Comment by agross** [comment]
Once I patched the config to `defaultUser: "Guest"` permissions are applied correctly.

**Comment by agross** [comment]
Another important aspect if the configured default user cannot be found: instead of moving on with the adapter initialization and essentially removing security ([quote](https://github.com/ioBroker/ioBroker.lovelace/blob/e0f9ac6d2e4a5f3d8e902d38439ea126456c3502/lib/modules/person.js#L91C87-L91C154): "all users will be able to read everything in this case.") I'd prefer if the adapter instance would stop. I was running with no security for a couple of weeks before noticing the logged warning yesterday.

**Comment by Garfonso** [comment]
> The issue in my case is that the `guest` user ID has the `Guest` user name. When selecting `Guest` on the UI, `defaultUser: 'guest'`

So this is wrong then. Hm. It seems what ever is stored as user comes from a undocumented admin function... hmpf... :-/

Your PR definitively won't work for cases where username and userid are different and a user enables authorization. The translation from name to id needs to stay as it was... 
Probably the adapter should augment the defaultUser to full ID and use it as ID. I honestly did not see that before.

**Comment by Garfonso** [comment]
Sorry for me being a bit grumpy last night. Foremost, thanks for your report and the work you put into fixing it. 

You are perfectly right, the adapter should not switch to admin if he does not find the configured user.
The misconception in the adapter was, that the `defaultUser` was supplied to the function `getUserIDFromName`. Not 100% sure why it was that way. Probably because I did not get that the frontend stores the last part of the user ID instead of the name. (I did not write that part and don't know about the `fillUsers` function it uses to fill the select options).
So I did change the adapter, so that `config.defaultUser` is augmented to be the full ID once (that was not necessary in older js-controller versions, another reason for the misconception emerging) and uses that if auth is disabled (or in the cases where no username is available).

That being said, the `getUserIDFromName` function is required in case authentication is enabled. In that case, we don't already have the ID, but the user supplies the username during login, and we need to figure out the ID from that. So the function needs to stay basically as it was.

You are welcome to test my last commits. I'll try to get a testing release ready, but for some reason I do not yet understand, two tests are currently failing (so the release process won't launch).

**Comment by agross** [comment]
Thank you, the git version (b6534ad6012c0b929ad15a8f144650bd83d20e80) appears to fix all the issues.

> That being said, the getUserIDFromName function is required in case authentication is enabled. 

That's something that I missed.

All good now. Thanks again!
