### ISSUE TITLE
Can't connect from Ariela app

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.lovelace#68]
I try to connect through the app for Android Ariela, all the stages of configuration are good, but when you need to download objects-an error occurs. Here is part of the Ariela program log:
```
01-08 19:43:37.046 29634 30227 D HA_HAConnectionTester: HAConnectionTester: final URL = http://192.168.1.100:8123/api/
01-08 19:43:37.075 29634 30228 D HA_HAConnectionTester: onResponse: called
01-08 19:43:37.077 29634 30228 E HA_HAConnectionTester: HAServerConnectionTester: JSON exception = org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: onResponse: message = <!DOCTYPE html>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <html lang="en">
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <head>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <meta charset="utf-8">
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <title>Error</title>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: </head>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <body>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: <pre>Cannot GET /api/</pre>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: </body>
01-08 19:43:37.077 29634 30228 D HA_HAConnectionTester: </html>

```
http://192.168.1.100:8123/api/ - I think the problem is this address. it doesn't exist
JS-Controller - 2.7.7
Lovelace adapter 1.0.6 (from github) should be 1.0.7 I think

**Comment by Garfonso** [comment]
You are probably right. The app probably talks to homeAssitant directly using the API. Maybe you can try to disable some features? Otherwise it can not be supported without a lot of effort.

**Comment by Anzic23** [comment]
of course! what should be done?

**Comment by Garfonso** [comment]
I tried the App myself and I do not think it is feasible to support it. It seems to be a lot more than just a frontend.

**Comment by Apollon77** [comment]
maybe contact the developers to check with them whats possible? :-)

**Comment by Garfonso** [comment]
I got it configured (I just had to enable authentication in lovelace adapter). Then I get an App with some functionality that is not working (because there is no full-fledged home assistant) and a button web interface which opens the browser.
If you enable webui in settings you get lovelace ui in the app. So you can get that to work. 
(if you restart the app, it seems you have to do the configuration again, because it will keep on complaining that it can not connect, so something is missing there). 

But I still think this is the right app for IoBroker + lovelace. Wallpanel / kiosk Browser are better alternatives for a control panel tablet IMHO (for IoBroker that is, for home assistant the app seems to add a lot of functionality). For a mobile lovelace works great in browser, tbh. We might want to look into cloud access. But I have no clue how that works and that is a completely different story.

**Comment by Anzic23** [comment]
I don't actually use the adapter fully. installed for the test. I found a discussion of this program and decided to try it. I found a bug and decided to share it so that you could fix it and others could use the app, because someone might find it very useful. I don't use it myself.
