### ISSUE TITLE
Feature Request: Add a config options to disable auto entity detection. 

### ISSUE THREAD

**Issue by Coalado** [ioBroker/ioBroker.lovelace#76]
I prefer to set up all entities manually (or by a custom script in my case).
Moreover, the auto-generated names are kind of weird and generate lots of duplicate warnings in the logs.

Thus I would love to see an option to disable the auto entity detection.

**Comment by Garfonso** [comment]
The last version changed the naming, so that it is based on the object name of the device.

Currently I do not think it is a sane idea to disable auto detection. It is the only way to create complex entities, ie entities that require more than one object (lights with more features than dimmer, Mediaplayer, geolocation, cover,....)
