### ISSUE TITLE
Cant get MPD device displayed with Lovelace UI

### ISSUE THREAD

**Issue by kalle2000** [ioBroker/ioBroker.lovelace#91]
Dear all,
I am pretty new to iobroker and lovelace (my main backbone is fhem). I installed the MPD adapter and assigned oth room and function to it:

![image](https://user-images.githubusercontent.com/16741825/82928342-66f33080-9f82-11ea-9d92-468ac60fd8c0.png)

Which entity do I have to enable for lovelace (entity type media player)? I tried both cards: media control and custom card [mini media player](https://github.com/kalkih/mini-media-player).

**Comment by Garfonso** [comment]
You'd need to setup the "state" object. It has the right role (media.state) but type is string. That is not accepted by type-detector (it wants boolean or number). So no media player entity for mpd, it seems... :-/

Not sure how to solve that. There is an object "song" with the role "media.state", too. Not sure what it does. You could try and see what happens if you configure a function & room for that.

This seems like an issue with the adapter to me and should be solved there, you might want to create an issue for mpd adapter stating that it should be made compatible with type-detector.

In the meantime a script (or even alias?, using the devices adapter) that translates the strings from state to boolean (stop = false, play = true) could be a workaround.

**Comment by kalle2000** [comment]
Got it working now with the help of type-detector.
Thanks
